# Generated by Django 5.1 on 2025-06-12 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_edited_messagehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='timestamp',
            new_name='edited_at',
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='previous_content',
            field=models.JSONField(),
        ),
    ]
