pipeline {
    agent any

    environment {
        VENV_PATH = "${WORKSPACE}/venv"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                     credentialsId: 'github-creds-id',
                     url: 'https://github.com/TheKingsident/alx-backend-python.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                    rm -rf $VENV_PATH
                    python3 -m venv $VENV_PATH
                    export PATH="$VENV_PATH/bin:$PATH"
                    export VIRTUAL_ENV="$VENV_PATH"
                    unset PYTHONPATH
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    export PATH="$VENV_PATH/bin:$PATH"
                    export VIRTUAL_ENV="$VENV_PATH"
                    unset PYTHONPATH
                    cd messaging_app
                    pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -rf $VENV_PATH'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
