pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                     credentialsId: 'github-creds-id',
                     url: 'https://github.com/TheKingsident/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd messaging_app
                    /opt/jenkins-venv/bin/pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    export DJANGO_SETTINGS_MODULE=messaging_app.settings
                    /opt/jenkins-venv/bin/pytest --junitxml=report.xml --verbose
                '''
            }
        }

        stage('Publish Report') {
            steps {
                echo 'Test execution completed'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            junit allowEmptyResults: true, testResults: 'messaging_app/report.xml'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
